[theme]
primaryColor = "#000000ff"
# backgroundColor = "#960d0dff"
backgroundColor = "#960d0dff"
# secondaryBackgroundColor = "#c7880aff"
secondaryBackgroundColor = "#c7880aff"
textColor = "#fafafa"
font = "Gill Sans"

[server]
enableStaticServing = true
